#!/usr/bin/env bash
# Container setup script — run once after cloning the repo.
# Generates PROTECTED_CONSTANTS.md from project.config.json.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
CONFIG="$SCRIPT_DIR/project.config.json"

if [ ! -f "$CONFIG" ]; then
  echo "ERROR: $CONFIG not found" >&2
  exit 1
fi

if ! OWNER=$(python3 -c "import json; print(json.load(open('$CONFIG'))['project']['repo_owner'])"); then
  echo "ERROR: failed to read repo_owner from $CONFIG" >&2
  exit 1
fi
if ! REPO=$(python3 -c "import json; print(json.load(open('$CONFIG'))['project']['repo_name'])"); then
  echo "ERROR: failed to read repo_name from $CONFIG" >&2
  exit 1
fi

cat > "$REPO_ROOT/PROTECTED_CONSTANTS.md" << EOF
# Protected Constants

> **DO NOT MODIFY THIS FILE.** It is generated by \`.claude/setup.sh\` from \`project.config.json\`.
> Re-run \`.claude/setup.sh\` if repo information changes.

| Constant | Value |
|----------|-------|
| repo_owner | $OWNER |
| repo_name | $REPO |
EOF

echo "Generated PROTECTED_CONSTANTS.md (owner=$OWNER, repo=$REPO)"

# Install pre-commit hook
HOOK_SRC="$SCRIPT_DIR/hooks/pre-commit"
HOOK_DST="$REPO_ROOT/.git/hooks/pre-commit"
if [ -f "$HOOK_SRC" ]; then
  cp "$HOOK_SRC" "$HOOK_DST"
  chmod +x "$HOOK_DST"
  echo "Installed pre-commit hook"
fi
